version: "3.9"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: "rinha"
    volumes:
      - ./conf/seed.js:/docker-entrypoint-initdb.d/seed.js:ro
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "175MB"
  api1: &api1
    hostname: api1
    build: ./src
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      ConnectionStrings__MongoDb: "mongodb://mongo:27017"
  api2:
    <<: *api1
    hostname: api2
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "175MB"
  nginx:
    image: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "20MB"