version: "3.9"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: "rinha"
    volumes:
      - ./conf/seed.js:/docker-entrypoint-initdb.d/seed.js:ro
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256GB"